import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className="flex">
        <div className="flex-1">{children}</div>
        <div className="w-1/3 bg-black p-2 border-gray-200 rounded-md border m-20">
          <h2 className="text-gray-200 text-center mb-0">Right Sidebar</h2>
        </div>
      </div>
    </html>
  )
}
